apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: header-based-rollout
spec:
  replicas: 5
  strategy:
    canary:
      canaryService: header-based-canary-svc
      stableService: header-based-stable-svc
      trafficRouting:
        alb:
          ingress: header-based-ingress
          rootService: header-based-root-svc
          servicePort: 80
      steps:
      - setWeight: 20
      - pause: {duration: 1h}
      - setWeight: 40
      - pause: {duration: 1h}
      - setWeight: 60
      - pause: {duration: 1h}
      - setWeight: 80
      - pause: {duration: 1h}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: header-based-app
  template:
    metadata:
      labels:
        app: header-based-app
    spec:
      containers:
      - name: header-based-app
        image: your-app-image:v1
        ports:
        - containerPort: 8080
