apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: header-based-rollout
spec:
  replicas: 3
  selector:
    matchLabels:
      app: header-based-app
  template:
    metadata:
      labels:
        app: header-based-app
    spec:
      containers:
      - name: header-based-app
        image: nginx:latest
  strategy:
    canary:
      canaryService: header-based-canary-svc  # Only canary service
      stableService: header-based-stable-svc   # Only stable service
      trafficRouting:
        alb:
          ingress: header-based-ingress
          servicePort: 80
      steps:
      - setWeight: 20
      - pause: {duration: 1h}
