---
apiVersion: v1
kind: Service
metadata:
  name: stable
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
   selector:
    app: my-app 
---
apiVersion: v1
kind: Service
metadata:
  name: canary
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
   selector:
    app: my-app  
